name: Ga-1
on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: step1
       run: |
          echo "hello Ga1"
          pwd
          ls -l
          hostnamectl
     - name: step2
       run : |
          wc -l /etc/passwd
          sudo apt update && sudo apt install python3
          python3 --version          
  job2:
    runs-on: ubuntu-latest
    - run: echo testinmg job2    
                